---
- name: bootstrap - install base packages
  apt:
    name: "{{ bootstrap_apt_packages }}"
    state: present
    update_cache: yes
  tags:
    - bootstrap
    - bootstrap-packages

- name: bootstrap - install tzdata
  apt:
    name: tzdata
    state: present
    update_cache: yes
  tags:
    - bootstrap
    - bootstrap-timezone

- name: bootstrap - set timezone
  timezone:
    name: "{{ bootstrap_timezone }}"
  tags:
    - bootstrap
    - bootstrap-timezone

- name: bootstrap - set hostname
  hostname:
    name: "{{ bootstrap_hostname }}"
  tags:
    - bootstrap
    - bootstrap-hostname

- name: bootstrap - install & configure NTP
  block:
    - name: bootstrap - install NTP package
      apt:
        name: ntp
        state: present
        update_cache: yes
    - name: bootstrap - configure NTP service
      template:
        src: templates/ntp.conf.j2
        dest: /etc/ntp.conf
      notify:
        - ntp - restart
  when: bootstrap_install_ntp
  tags:
    - bootstrap
    - bootstrap-ntp